language: scala
scala:
  - 2.11.7
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - sbt clean coverage test &&
    sbt coverageAggregate
after_success:
  - sbt coveralls
script:
  - sbt clean coverage test coverageReport coverageAggregate
before_install:
  - pip install --user codecov
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b7dcd854b987168e105e
    on_success: change
    on_failure: always
    on_start: never
